export const products = [
  {
    id: '1',
    slug: '1',
    name: 'Корм для собак1',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '4',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '2',
    slug: '2',
    name: 'Корм для собак2',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '3',
    slug: '3',
    name: 'Корм для собак3',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '4',
    slug: '4',
    name: 'Корм для собак4',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '5',
    slug: '5',
    name: 'Корм для собак5',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '6',
    slug: '6',
    name: 'Корм для собак6',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '7',
    slug: '7',
    name: 'Корм для собак7',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '8',
    slug: '8',
    name: 'Корм для собак8',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '9',
    slug: '9',
    name: 'Корм для собак9',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '10',
    slug: '10',
    name: 'Корм для собак10',
    productCode: '1111',
    price: '800',
    priceDiscount: '',
    categories: '',
    disciuntPercentage: '',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '11',
    slug: '11',
    name: 'Корм для собак11',
    productCode: '1111',
    price: '800',
    priceDiscount: '680',
    categories: '',
    disciuntPercentage: '15',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '12',
    slug: '12',
    name: 'Корм для собак12',
    productCode: '1111',
    price: '800',
    priceDiscount: '720',
    categories: '',
    disciuntPercentage: '10',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '13',
    slug: '13',
    name: 'Корм для собак13',
    productCode: '1111',
    price: '800',
    priceDiscount: '720',
    categories: '',
    disciuntPercentage: '10',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '14',
    slug: '14',
    name: 'Корм для собак14',
    productCode: '1111',
    price: '800',
    priceDiscount: '720',
    categories: '',
    disciuntPercentage: '10',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '15',
    slug: '15',
    name: 'Корм для собак15',
    productCode: '1111',
    price: '800',
    priceDiscount: '720',
    categories: '',
    disciuntPercentage: '10',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
  {
    id: '16',
    slug: '16',
    name: 'Корм для собак16',
    productCode: '1111',
    price: '800',
    priceDiscount: '720',
    categories: '',
    disciuntPercentage: '10',
    typesProduct: '',
    image: '',
    rating: '5',
    manufacturer: {
      id: '1',
      trade_brand: 'Brand',
      country: 'country',
      country_brand_registration: 'Country brand registration',
    },
    description:
      'Red Point Donut Хутряний лежак із подушкою для котів і собак, рожевий',
    images: { id: '1', image: '', product: '' },
  },
];
